import { format } from 'date-fns';
import Head from 'next/head'
import { useState } from 'react'
import { Datepicker } from '../components/Datepicker'
import { AvatarIcon } from '../components/Icons'

export default function Home() {

  const [selectedDate, setSelectedDate] = useState(new Date());

  function handleSelectedDate(selectedDate: Date) {
    setSelectedDate(selectedDate)
  }

  return (
    <div>
      <Head>
        <title>Agenda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mustache_16.png" />
      </Head>

      <div className="flex flex-col items-center mt-8">

        <Datepicker handleSelectedDate={handleSelectedDate} />

        <div className="w-[546px] p-4 bg-white border rounded-lg shadow-md sm:p-8 dark:bg-gray-800 dark:border-gray-700">
          <div className="flex items-center justify-between mb-4">
            <h5 className="text-xl font-bold leading-none text-gray-900 dark:text-white">Agenda do dia {format(selectedDate, "dd/MM/yyyy")}</h5>
          </div>
          <div className="flow-root">
            <ul role="list" className="divide-y divide-gray-200 dark:divide-gray-700">
              <li className="py-3 sm:py-4 cursor-pointer">
                <div className="flex items-center space-x-4">
                  <div className="flex-shrink-0">
                    <AvatarIcon />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-gray-900 truncate dark:text-white">
                      Neil Sims
                    </p>
                    <p className="text-sm text-gray-500 truncate dark:text-gray-400">
                      email@windster.com
                    </p>
                  </div>
                  <div className="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
                    09:00
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>

    </div>
  )
}
